#!/bin/sh
#
# automatically push after commit
# Credential handling options:
#  - hardcode credentials in URL 
#  - use ssh with key auth 
#  - https://git-scm.com/docs/git-credential-store
#  - git credential helper on windows

# Redirect output to stderr, uncomment for more output for debugging
# exec 1>&2

git push
